export const SET_LOADING = 'SET_LOADING';
export const FARM_ERROR = 'FARM_ERROR';
export const FARM_TYPE = 'FARM_TYPE';
export const FARM_STATE = 'FARM_STATE';
export const FARM_LGA = 'FARM_LGA';
export const GET_FARMS = 'GET_FARMS';

export const EQUIPMENT_SERVICE_LIST_SUCCESS = 'EQUIPMENT_SERVICE_LIST_SUCCESS'
export const EQUIPMENT_REQUEST_LIST_SUCCESS = 'EQUIPMENT_REQUEST_LIST_SUCCESS'


export const EQUIPMENT_LIST_SUCCESS = 'EQUIPMENT_LIST_SUCCESS'
export const EQUIPMENT_LIST_FAIL = 'EQUIPMENT_LIST_FAIL'

export const EQUIPMENT_CREATE_SUCCESS = 'EQUIPMENT_CREATE_SUCCESS'
export const EQUIPMENT_CREATE_FAIL = 'EQUIPMENT_CREATE_FAIL'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export  const USER_DETAILS = 'USER_DETAILS'
export const ADD_FARM = 'ADD_FARM';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_FARM = 'UPDATE_FARM';
export const DELETE_FARM = 'DELETE_FARM';
