export const SET_LOADING = 'SET_LOADING';
export const FARM_ERROR = 'FARM_ERROR';
export const FARM_TYPE = 'FARM_TYPE';
export const FARM_STATE = 'FARM_STATE';
export const FARM_LGA = 'FARM_LGA';
export const GET_FARMS = 'GET_FARMS';

export const EQUIPMENT_SERVICE_LIST_SUCCESS = 'EQUIPMENT_SERVICE_LIST_SUCCESS'
export const EQUIPMENT_REQUEST_LIST_SUCCESS = 'EQUIPMENT_REQUEST_LIST_SUCCESS'


export const EQUIPMENT_LIST_SUCCESS = 'EQUIPMENT_LIST_SUCCESS'
export const EQUIPMENT_LIST_FAIL = 'EQUIPMENT_LIST_FAIL'

export const EQUIPMENT_CREATE_SUCCESS = 'EQUIPMENT_CREATE_SUCCESS'
export const EQUIPMENT_CREATE_FAIL = 'EQUIPMENT_CREATE_FAIL'
